# Generated by Django 5.0.6 on 2024-07-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
